version: "3.9"
services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "54321:5432"
    volumes:
      - "lms-data:/var/bin/postgresql/data"

volumes:
  lms-data:

