"""New

Revision ID: 8f28ce7a1caa
Revises: 29f3cb57eeea
Create Date: 2023-06-27 23:17:05.223458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f28ce7a1caa'
down_revision = '29f3cb57eeea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
